# Generated by Django 3.1 on 2020-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakedatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.TextField(),
        ),
    ]
